import { CatalogProductResponse } from '../model/catalog-product-response.model';

export const MOCK_PRODUCTS: CatalogProductResponse[] = [
  { productId:'1', productName:'iPhone 15 Pro', description:'Titane noir, 256GB. Puce A17 Pro, appareil photo 48MP, Dynamic Island.', price:1200, promotionActive:true,  promotionPrice:999, imageUrl:'https://picsum.photos/id/1/500/500',   shopName:'Apple Store',  shopOpen:true,  inStock:true,  availableQuantity:5,  distanceKm:1.2, categoryId:'tech'   },
  { productId:'2', productName:'AirPods Pro 2',  description:'Réduction de bruit active. Audio Spatial personnalisé. 30h autonomie.', price:279, promotionActive:false, imageUrl:'https://picsum.photos/id/20/500/500',  shopName:'Tech Shop',    shopOpen:true,  inStock:true,  availableQuantity:15, distanceKm:3.5, categoryId:'audio'  },
  { productId:'3', productName:'Samsung Galaxy S24', description:'Galaxy AI intégrée. Écran Dynamic AMOLED 6.7". Triple capteur 200MP.', price:950, promotionActive:true,  promotionPrice:850, imageUrl:'https://picsum.photos/id/48/500/500',  shopName:'Samsung Hub',  shopOpen:true,  inStock:true,  availableQuantity:8,  distanceKm:2.1, categoryId:'tech'   },
  { productId:'4', productName:'Sony WH-1000XM5', description:'Casque sans fil premium. Réduction de bruit leader. 30h autonomie.', price:399, promotionActive:false, imageUrl:'https://picsum.photos/id/100/500/500', shopName:'Audio Pro',    shopOpen:false, inStock:true,  availableQuantity:3,  distanceKm:0.8, categoryId:'audio'  },
  { productId:'5', productName:'iPad Air M2',   description:'Puissance et finesse. Puce M2. Écran Liquid Retina 11". Apple Pencil Pro.', price:699, promotionActive:false, imageUrl:'https://picsum.photos/id/119/500/500', shopName:'Apple Store',  shopOpen:true,  inStock:true,  availableQuantity:10, distanceKm:1.2, categoryId:'tech'   },
  { productId:'6', productName:'Apple Watch Ultra 2', description:'Pour aventuriers. Titanium. GPS double fréquence. Autonomie 60h.', price:899, promotionActive:true,  promotionPrice:799, imageUrl:'https://picsum.photos/id/160/500/500', shopName:'Apple Store',  shopOpen:true,  inStock:false, availableQuantity:0,  distanceKm:1.5, categoryId:'tech'   },
  { productId:'7', productName:'Nintendo Switch OLED', description:'Modèle OLED 7". Dock amélioré. 64GB de stockage interne.', price:349, promotionActive:false, imageUrl:'https://picsum.photos/id/250/500/500', shopName:'Gaming Zone',  shopOpen:true,  inStock:true,  availableQuantity:20, distanceKm:5.4, categoryId:'gaming' },
  { productId:'8', productName:'PS5 Slim',      description:'Console Sony. SSD ultra-rapide. DualSense. 4K 120fps. Ray-tracing.', price:549, promotionActive:true,  promotionPrice:499, imageUrl:'https://picsum.photos/id/342/500/500', shopName:'Gaming Zone',  shopOpen:true,  inStock:true,  availableQuantity:2,  distanceKm:5.4, categoryId:'gaming' },
  { productId:'9', productName:'Clavier Mécanique RGB', description:'RGB personnalisable. Switchs red linéaires. TKL. Anti-ghosting 100%.', price:120, promotionActive:false, imageUrl:'https://picsum.photos/id/436/500/500', shopName:'PC Master',    shopOpen:true,  inStock:true,  availableQuantity:12, distanceKm:4.2, categoryId:'tech'   },
  { productId:'10',productName:'Souris Gamer Pro', description:'25 600 DPI. Optique PixArt. USB-C. 6 boutons programmables.', price:80, promotionActive:true,  promotionPrice:59,  imageUrl:'https://picsum.photos/id/60/500/500',  shopName:'PC Master',    shopOpen:true,  inStock:true,  availableQuantity:25, distanceKm:4.2, categoryId:'tech'   },
];
